### ISSUE TITLE
What's the use of Endpoint?

### ISSUE THREAD

**Issue by davidpelaez** [trailblazer/trailblazer#100]
Hi Nick.

I tried to understand how Endpoint and Controller are connected but I don't think I get what the Endpoint class does. I wonder if you would you give me a hint to grasp the intention and connect the dots. I was very interested by the comment  that says it `# Encapsulates HTTP-specific logic needed before running an operation.`

I see in the Operation docs that I can do `res, op = run MyOp` but so far I don't understand what the result would be. Is this the return value of the operation process method? Do you intend to use this as a status signaling optional variable that could be used to match the execution of the operation to HTTP codes in cases where exceptions won't do? Some of these cases are for instance a successful execution of two different operations mapping to different HTTP codes. The first one, listing the items of a resources (`GET /items`) would imply a `200 OK`. However another successful operation creating an item would require a `201 Created`. These are opposed to catching a `::Trailblazer::NotAuthorizedError` and mapping to a `401` there's an extra piece of data to convert the execution to an HTTP status code. 

I wonder if this is somewhat related. Clearly without a way to match a set of params to an operation and handling the HTTP related parts the controllers needs to exist even though with minimal responsibilities. 

Sorry for the odd questions about the intention and what it actually does, I really tried to get it on my own before asking. It's just that I have been wondering recently if a mini controller together with `lotus-router` would be enough without all the full blown benefits of the lotus-controller that are not needed when using operations. 

Maybe the whole Endpoint class is related to this and I would be reimplementing a part of something you've already done. Is that what the comment cited about is about?

**Comment by apotonick** [comment]
As for Lotus, I think you don't "want" the full-blown controller, because Trailblazer does embrace all the business logic. 

The controller should only do HTTP-specific logic. Here's how I think about it.

1. Controller (Lotus/Rails) gets called and dispatches to operation.
2. `Operation::run` is invoked, operation does its work, and returns either `true` or `false`. That's the result from the validation. So, if anything goes wrong, the operation has the validity boolean to tell the caller.
3. The controller then interprets that. In a HTTP environment, this means that you have to compute a status code, and so on. For example, the controller knows that it calls a `Create` operation, a valid result means `201`, and so on.
4. So far, we have exceptions only for authorization breaches, which have to be caught and interpreted in the controller, too.

My initial idea was to provide a generic implementation in `Endpoint` but I'm not so sure anymore if we really need it. What do you think?

**Comment by davidpelaez** [comment]
I agree with your steps. Either we launch an exception when validations don't pass, or return the boolean as you suggest. `res,op = run Web::Operations::CreateComment` and `res` is actually the operation and `op` is nil.  That's not currently implemented right? Only the part of the authorization error throws an exception at the moment. I checked something like this:

Regarding the Endpoint class. When talking about the helpers in the controller as in here https://github.com/apotonick/trailblazer/blob/468e5ad9b436a76ee3f1384fa87546a7459d1ffc/lib/trailblazer/operation/controller.rb#L60 I don't think it's needed.

However when seeing it as a generic starting point to function as a controller replacement I think there's a use. The computation of the HTTP code could vary slightly in some cases but sticking to Rails conventions is an excellent starting point that most people will agree with. However if we can agree on a pattern we could provide a generic version to inherit from or configure in order to handle body parsing and other router related transformations. That would offer a simple way to hook it into any router without actually needing the complete frameworks controller. It's quite specialized so I don't know how many people would actually use it. I would certainly use it, it's the exact thing I was working on during the weekend!

So, to include or not to include a generic starting point that encapsulate HTTP related stuff to be used a controller replacement? If you want to include it we could send an initial implementation @simon0191 is working on.

**Comment by davidpelaez** [comment]
Why don't we have the `InvalidContract` exception everywhere so that can be rescued together with `::Trailblazer::NotAuthorizedError`? I saw it's being used here for testing purposes I suppose:

https://github.com/apotonick/trailblaxzer/blob/master/lib/trailblazer/operation.rb#L152-L155

The only thing is that the errors should be passed as an object, not a string for it to be handled in some way if needed, ej: serializing then in some way.

**Comment by davidpelaez** [comment]
I just noticed that `Operation.run` does indeed return the boolean and raises a ` ::Trailblazer::NotAuthorizedError` but the controller's helper `run` only raises on the latter, never the returns the former.

I noted because of the single return value in https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/operation/controller.rb#L25-L31 as opposed to the array returned in https://github.com/apotonick/trailblazer/blob/d6c50cc4c84394d10135207e5662d7ee0f72af84/lib/trailblazer/operation.rb#L13-L22

I would suggest that they have the exact same behaviour. It's weird to have different result of `run` within the library.

PS: This conversation is getting messy, please let me know if you want to split into other issues.

**Comment by apotonick** [comment]
It's only messy because you didn't read the docs! :grimacing: http://trailblazer.to/gems/operation/api.html (call vs. run).

The return value for `run` changes, but I agree that this might be confusing (for people who don't read the docs hahaha).

I don't think exceptions are a good way to transport flow information. For example, in a JSON API endpoint, `Endpoint` and the operation's representer have to work together to compile the result document, and in an error case, an exception will only be annoying to handle (and _very_ slow. which does start mattering when you have hundredthousands of request per second).

What do you mean by "body parsing"? This has to happen in the operation using its representer. This is very different to all the other "frameworks" because they don't have the technology for deserialization, so what exactly are you thinking of?

I think we agree on most of the responsibilities for the `Endpoint`, though. Yeah, the goal is to use `Endpoint` (maybe even via the `Controller` module, which works in Lotus and Sinatra, too) and really use the framework's controller only as a HTTP dispatcher.

**Comment by apotonick** [comment]
All here now! http://trailblazer.to/gems/operation/2.0/endpoint.html

@davidpelaez Can I still count on you helping extending `Endpoint`, adding more matchers, more handlers e.g. for Rack, etc.? :heart:

**Comment by davidpelaez** [comment]
Yes sir, working on it tomorrow since it's a holiday in Colombia. @apotonick
