### ISSUE TITLE
NameError from extend Contract::DSL

### ISSUE THREAD

**Issue by swinner2** [trailblazer/trailblazer#186]
```
class Foo::Bar
  class Create < Trailblazer::Operation
    extend Contract::DSL
    
  end
end
```

`NameError: uninitialized constant Foo::Bar::Contract::DSL`

however this seems to work fine
```
class Foo::Bar
  class Create < Trailblazer::Operation
    extend Create::Contract::DSL
    
  end
end
```

**Comment by apotonick** [comment]
Thanks @trkoch! The problem here is/was that we advised TRB devs to use naming such as `Foo::Bar::Contract::Create` for, say, a _create_ contract in the foo/bar domain. At the same time we have a constant `Trailblazer::Operation::Contract`, so those could overlap. And, yes, you're absolutely right, we keep having to explain the compact vs. explicit namespacing issue :grimacing:

**Comment by tonekk** [comment]
Hi @apotonick ,

what would be your suggestion to handle this case?
I see two options here:

1) Switch back to compact style
2) Write `Trailblazer::Contract` instead of `Contract` inside of the operations

Off the top of my head I'd say I'm in favour of the latter, although that makes our Operations differ from the trailblazer docs. What would you do?

**Comment by apotonick** [comment]
I usually put contracts under the `Form` namespace. It was a bit naive to introduce the `Contract::<macro name>` constant. And after all, when using Reform, your contract *is* actually a form. Maybe we should change that in future docs? Thanks for your comment, @tonekk!
