### ISSUE TITLE
how deal with namespaces?

### ISSUE THREAD

**Issue by aronwolf90** [trailblazer/trailblazer#197]
I am experimenting with trailblazer in a new website. This website has multiple namespaces. How deal with namespaces in trailblazer concepts-structure? In my case there are 3 namespaces:
- Frontend part (without namespace)
- Admin (administration)
- Api (api/v1)

I can imagine that i am not the only one who that have this question. :)

**Comment by fernandes** [comment]
hey @aronwolf90 

Are you have any problem with namespace? because you can normally use as in any regular ruby application, the only thing you need to pay attention is the structure based on [trailblazer-loader](https://github.com/trailblazer/trailblazer-loader)

consider you are using [explicit-plural](https://github.com/trailblazer/trailblazer-loader#explicit-plural) (my preferred one)

you have a `Comment` concept, you can use exactly as in the README, and nest concepts in concepts if you use something like [Uber::Builder](https://github.com/apotonick/uber#builder) to decide if it's gonna process the request using `Comment` or `Comment::Admin` (in case user is admin or something like that)

The same way you can nest concepts, you can organize in different namespaces:

`Comment::Create` -> `app/concepts/comment/operations/create.rb`
`Admin::Comment::Create` -> `app/concepts/admin/comment/operations/create.rb`
`Api::V1::Comment::Create` -> `app/concepts/api/v1/comment/operations/create.rb`

Just prepend the namespace and voilá... it's gonna work 😉 

was this helpful?

**Comment by aronwolf90** [comment]
It was more how to structure than how get it working, but your example answer my question, thanks :)

**Comment by fernandes** [comment]
uow, glad it helped :)
