### ISSUE TITLE
Going through the happy path

### ISSUE THREAD

**Issue by bolshakov** [trailblazer/trailblazer#51]
It would be great if I could compose operations in monadic manner.
For example:

``` ruby
MyOperation[params].map do |result|
  AnotherOperation.run(result).map do |another_result|
    another_result * 2
  end
end
```

or apply side-effecting function: 

``` ruby
MyOperation[params].each do |result|
  puts "This is result: #{result}"
end.or_else do |errors|
  fail errors.full_messages.join(', ')
end
```

What do you think?

**Comment by apotonick** [comment]
Yeah, I am thinking about a way to nest operations, I was even considering using Organizers.

We should collect requirements here.

Regarding the `or_else`, check out the `Controller` module, there's an `else` function which you can play with. Great idea!

**Comment by bolshakov** [comment]
I'v seen controller's else but whole controller module it too tightly bound with [model](https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/operation/controller.rb#L67-L68) and with rails controller

I\m new user of trailblazer so may be  missed something. I'l look at Organizers

**Comment by eljojo** [comment]
Hi everyone!
I think that if we want to avoid business logic duplication (or pushing it back to the models) there has to be a way in Trailblazer to nest operations.

I found this issue because I'm implementing Trailblazer in a project and had this need.
Here's a sample use case:

Let's say I have a ``Comment`` model that has some business logic (spam validation, moderation queue, whatever).
My project has a ``Photo`` and ``Article`` models, both unrelated to each other, but they all can have multiple comments.
My idea would be to have a ``Comment::Create`` operation that would have all the comment business logic and then nest it in ``Photo::Create`` and ``Article::Create``.

Right now, the most *trailblazer way* of doing it, is just having two operations: ``Photo::Create`` and ``Article::Create``.
In each operation, the contract would have a ``collection`` to ``:comments``, in which we would validate.
Also, in the ``#process`` method from the operation I'd put the business logic.
Alternatively, I could push the business logic to the model, but that sounds like an even worse decision.

**Comment by apotonick** [comment]
Our huge advantage is that we have all the technology in place and now can think about optimising how it plays together in more complex situations.

I am currently working on callbacks, which you should not confuse with Rails callbacks. Here, you can dispatch logic based on "events" that were tracked in the original object graph.

```ruby
callback(:upload) do
  on_change :upload_file!, property: :file
end
```

You then invoke the callback group manually where you need it. I call this _Imperative Callback_.

```ruby
def process(params)
  dispatch!(:upload) #=> will run :upload_file! if contract.file has changed.
```

This is a completely generic mechanism and decoupled from the rest of Trailblazer. You could use this to trigger nested operations like @eljojo , which is absolutely the "Trailblazer way" (haha).

My idea for handling side-effects as @bolshakov mentions it works when calling `dispatch!`.

```ruby
class Invoker < Trailblazer::Hook
  def skip?(current, previous, next)
    # here you can decide whether to execute the next callback
  end

  def rescue(current, previous, next)
    # here you handle errors.
  end
end

dispatch!(:upload, invoker: Hook)
```

Of course, we could make that less verbose, but my point is that defining what to call in a group and how it's called is completely separated (`Callback::Group` and `Hook`).

**Comment by apotonick** [comment]
Some real-world examples in pseudo-code would help!!! :beers:

**Comment by janpieper** [comment]
Any news?

**Comment by apotonick** [comment]
I think using ActiveInteractor or dry-transaction within operations and making those easily available with a simple abstraction in `Operation` is key here, the more I work with it.

**Comment by apotonick** [comment]
Yepp: https://github.com/trailblazer/operation/wiki/Roadmap#result-object

**Comment by apotonick** [comment]
This now works. http://trailblazer.to/gems/operation/2.0/pipetree.html

**Comment by eljojo** [comment]
this is amazing! Congrats on the great work!
